"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w38y2pHGr3i
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

import BrandLogo from "@public/images/brandLogo.svg";

export default function Footer() {
  return (
    <footer className="bg-neutral-50 py-6 px-6 md:py-12">
      <div className="container mx-auto max-w-7xl grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 px-4 md:px-6">
        <div className="flex flex-col gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <BrandLogo
              color="primary dark:white"
              style={{ width: 120, transform: `translateY(2px)` }}
            />
          </Link>
          <p className="text-muted-foreground text-sm">
            Free, but Better.
          </p>
        </div>
        <div className="flex flex-col gap-2">
          <h4 className="text-base font-semibold">프로덕트</h4>
          <nav className="flex flex-col gap-1">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              폰트 찾아보기
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              서비스 소개
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              FAQ
            </Link>
          </nav>
        </div>
        <div className="flex flex-col gap-2">
          <h4 className="text-base font-semibold">지원</h4>
          <nav className="flex flex-col gap-1">
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              폰트 제보하기
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              광고 문의
            </Link>
            <Link href="#" className="text-sm hover:underline" prefetch={false}>
              라이센스
            </Link>
          </nav>
        </div>
        <div className="flex flex-col gap-2">
          <p className="text-muted-foreground text-sm">
            모든 폰트의 저작권은 각 폰트의 제작자에 있습니다. 라이센스 관련
            문의는 폰트 소개란에 기재된 제작자에게 문의해주십시오.
          </p>
        </div>
      </div>
      <div className="container mx-auto max-w-7xl px-4 md:px-6 mt-8 text-center">
        <p className="text-sm text-muted-foreground">
          &copy; 2024 Design eXperience™. All rights reserved.
        </p>
      </div>
    </footer>
  );
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
